<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>haproxy.cfg</string>
    </array>
    <key>name</key>
    <string>Haproxy</string>
    <key>patterns</key>
    <array>
      <!-- Comments -->
      <dict>
        <key>match</key>
        <string>\#.*</string>
        <key>name</key>
        <string>comment</string>
      </dict>
      <!-- IP Address -->
      <dict>
        <key>match</key>
        <string>\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?):\d{1,5}\b</string>
        <key>name</key>
        <string>constant.numeric</string>
      </dict>
      <!-- Wildcard Bind Line -->
      <dict>
        <key>match</key>
        <string>\b\*:\d{1,5}\b</string>
        <key>name</key>
        <string>constant.numeric</string>
      </dict>
      <!-- Ciphers -->
      <dict>
        <key>match</key>
        <string>\bciphers\s+[^\b]+\b</string>
        <key>name</key>
        <string>string.other</string>
      </dict>
      <!-- Numeric Constants -->
      <dict>
        <key>match</key>
        <string>\b(\d+|(\d+)s)\b</string>
        <key>name</key>
        <string>constant.numeric</string>
      </dict>
      <!-- Stick Table Parameters -->
      <dict>
        <key>match</key>
        <string>\b(key|server_id|gpc0|gpc0_rate|gpc1|gpc1_rate|conn_cnt|conn_cur|conn_rate|sess_cnt|sess_rate|http_req_cnt|http_req_rate|http_err_cnt|http_err_rate|bytes_in_cnt|bytes_in_rate|bytes_out_cnt|bytes_out_rate)\b</string>
        <key>name</key>
        <string>constant.language</string>
      </dict>
      <!-- Sections -->
      <dict>
        <key>match</key>
        <string>\b^(aggregations|backend|defaults|frontend|global|listen|peers|userlist)\b</string>
        <key>name</key>
        <string>support.class</string>
      </dict>
      <!-- Keywords -->
      <dict>
        <key>match</key>
        <string>\b(acl|appsession|backlog|balance|bind|bind-process|block|ca-base|chroot|compression|cookie|cpu-map|crt-base|daemon|default-server|default_backend|description|disabled|dispatch|enabled|errorfile|errorloc|errorloc302|errorloc303|force-persist|from|fullconn|grace|hash-type|id|ignore-persist|lua-load|log-format|log|mode|monitor\s+fail|monitor-net|monitor-uri|nbproc|peer|persist\s+rdp-cookie|rate-limit\s+sessions|redirect|reqadd|reqallow|reqdel|reqdeny|reqiallow|reqidel|reqideny|reqipass|reqirep|reqisetbe|reqitarpit|reqpass|reqrep|reqsetbe|reqtarpit|retries|rspadd|rspdel|rspdeny|rspidel|rspideny|rspirep|rsprep|server|source|ssl-default-bind-(ciphers|options)|to|unique-id-(format|header)|use(_backend|-server))\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Parameters As Keywords -->
      <dict>
        <key>match</key>
        <string>^\s*\b(maxconn)\b|^\s*\b(user)\b|^\s*\b(group)\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Capture Keyword Combinations -->
      <dict>
        <key>match</key>
        <string>\b(capture\s+(cookie|request\s+header|response\s+header))\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Http Keyword Combinations -->
      <dict>
        <key>match</key>
        <string>\b(status|rstatus|rstring|string)\s+.+</string>
        <key>name</key>
        <string>string.quoted.double</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(http-check\s+(disable-on-404|expect|send-state)|http-(request|response))\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Option keyword combinations -->
      <dict>
        <key>match</key>
        <string>\b(option\s+(abortonclose|accept-invalid-http-request|accept-invalid-http-response|allbackups|checkcache|clitcpka|contstats|dontlog-normal|dontlognull|forceclose|forwardfor|http-no-delay|http-pretend-keepalive|http-server-close|http-use-proxy-header|httpchk|httpclose|httplog|http_proxy|independent-streams|ldap-check|log-health-checks|log-separate-errors|logasap|mysql-check|pgsql-check|nolinger|originalto|persist|redispatch|redis-check|smtpchk|socket-stats|splice-auto|splice-request|splice-response|srvtcpka|ssl-hello-chk|tcp-check|tcp-smart-accept|tcp-smart-connect|tcpka|tcplog|transparent))\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Stats keyword combinations -->
      <dict>
        <key>match</key>
        <string>\b(stats\s+(admin|auth|bind-process|enable|hide-version|http-request|realm|refresh|scope|show-desc|show-legends|show-node|socket|timeout|uri))\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Stick keyword combinations -->
      <dict>
        <key>match</key>
        <string>\b(stick\s+(match|on|store-request|store-response)|stick-table)\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Tcp* keyword combinations -->
      <dict>
        <key>match</key>
        <string>\b(tcp-request\s+(connection|content|inspect-delay)|tcp-response\s+(content|inspect-delay))\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Timeout keyword combinations -->
      <dict>
        <key>match</key>
        <string>\b(timeout\s+(check|client|connect|http-keep-alive|http-request|queue|server|tarpit|tunnel))\b</string>
        <key>name</key>
        <string>keyword</string>
      </dict>
      <!-- Unquoted strings -->
      <dict>
        <key>match</key>
        <string>\b(\ˇ\w+\d+)\"\b</string>
        <key>name</key>
        <string>string.unqouted</string>
      </dict>
      <!-- Quoted strings -->
      <dict>
        <key>match</key>
        <string>\".*\"</string>
        <key>name</key>
        <string>string.quoted</string>
      </dict>
      <!-- Subcommand functions / sub-keywords / known parameters -->
      <dict>
        <key>match</key>
        <string>\b(add-header|admin|append-slash|backup|ca-file|check|code|connect|crt|debug|del-header|drop-query|error-limit|found|group|http|https|insecure-password|len|level|maxconn|mark-down|notice|no-sslv3|on-error|on-marked-up|optional|origin|path_beg|port|prefix|rise|roundrobin|scheme|set-header|shutdown-backup-sessions|ssl|status|tcp|tune|use-service|user|verify)\b</string>
        <key>name</key>
        <string>support.variable</string>
      </dict>
      <!-- Subcommand functions / sub-keywords add/set/del-* combinations -->
      <dict>
        <key>match</key>
        <string>\b(add-(header|acl|map|var)|del-(acl|header|map|var)|set-(header|nice|log-level|path|query|uri|tos|mark|priority-classs|priority-offset|var)\replace-(header|value))\b</string>
        <key>name</key>
        <string>support.variable</string>
      </dict>
      <!-- Operators -->
      <dict>
        <key>match</key>
        <string>\s+(or|\|\||!)\s+</string>
        <key>name</key>
        <string>keyword.operator</string>
      </dict>
      <!-- Control flow -->
      <dict>
        <key>match</key>
        <string>\b(if|unless|rewrite)\b</string>
        <key>name</key>
        <string>keyword.control</string>
      </dict>
      <!-- Parameters -->
      <dict>
        <key>match</key>
        <string>%\[[^\]]+\]</string>
        <key>name</key>
        <string>variable.parameter</string>
      </dict>
      <!-- Functions -->
      <dict>
        <key>match</key>
        <string>\b(capture\.(req|res)\.hdr|http_auth)\b</string>
        <key>name</key>
        <string>entity.name.function</string>
      </dict>
      <!-- Everything else -->
      <dict>
        <key>match</key>
        <string>\/[\w\.\-\?=]+</string>
        <key>name</key>
        <string>variable.parameter</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.haproxy</string>
    <key>uuid</key>
    <string>4b8aa860-7a71-426a-9e6c-38faaff762bc</string>
  </dict>
</plist>
